### ISSUE TITLE
Docs notes

### ISSUE THREAD

**Issue by glattercj** [activeshadow/phenix-docs#1]
- `Experiments`
  - [x] "Optionally, you can use the --dry-run flag to do everything __*expect*__ call out to minimega."
- `User administration in phenix`
  - [x] "Choose the Create Account link off the login page and complete all fields __*one*__ the Create a New Account dialogue."
- `VMs`
  - [x] "Available commands"
    - This looks wonky...should be a list? 
  - [x] "Modify VM Settings"
    - This looks wonky...should be a list?
  - [ ] Details about creating a snapshot and creating a backing image?
  - [x] Nothing about clicking on screenshot to open VNC tab?
  - [ ] Screenshots of exp details page? VNC page?

**Comment by activeshadow** [comment]
@glattercj you want screenshot of exp details page in the documentation for VMs or experiments?

**Comment by glattercj** [comment]
Probably within the VMs, since the first paragraph talks about going to the VMs info / running experiment tab:

> The experiment must be started; click on the experiment name to enter the Running Experiment component. ...
